[package]
name = "pyseph/objectcache"
version = "1.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "A robust, blazing fast part cache for Roblox."
license = "MIT"